#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
#
# Author:    Yuansheng Sun  yuansheng-sun@uiowa.edu
# Copyright: University of Iowa 2006
#
# Filename:  SConscript
#
 	
Import( 'env' )
env = env.Clone()


conf = Configure(env)

#GLUT library config
if not conf.CheckLibWithHeader( 'glut', 'GL/glut.h', 'C' ):
	print 'glut library must be installed!'
	Exit(1)

#GL library config
if not conf.CheckLib( 'GL' ):
	print 'GL library must be installed!'
	Exit(1)

#GLU library config
if not conf.CheckLib( 'GLU' ):
	print 'GLU library must be installed!'
	Exit(1)

env = conf.Finish()


env.Append( LIBS = [ 'deconv', 'GL', 'GLU', 'glut', 'fftw3', 'fftw3f' ] )
env.Append( LIBPATH = [ '#build/libdeconv' ] )


ViewSlices_sources = [ 'gnuplot_i.cc', 'ViewerUtils.cc', 'ViewSlices.cc' ]
ViewCube_sources = [ 'gnuplot_i.cc', 'ViewerUtils.cc', 'ViewCube.cc' ]


ViewSlices = env.Program( 'ViewSlices', ViewSlices_sources) 	
ViewCube = env.Program( 'ViewCube', ViewCube_sources) 	


env.Alias('install', env.Install( env['BIN_DIR'], ViewSlices))
env.Alias('install', env.Install( env['BIN_DIR'], ViewCube))
