#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
#
# Author:    Yuansheng Sun  yuansheng-sun@uiowa.edu
# Copyright: University of Iowa 2006
#
# Filename:  SConscript
#

Import( 'env' )
env = env.Clone()

env.Alias('install', env.Install( env['BIN_DIR'], "Convert2BMPs" ))
env.Alias('install', env.Install( env['BIN_DIR'], "Convert2JPGs" ))
env.Alias('install', env.Install( env['BIN_DIR'], "Convert2PGMs" ))
env.Alias('install', env.Install( env['BIN_DIR'], "Convert2PNGs" ))
env.Alias('install', env.Install( env['BIN_DIR'], "Convert2TIFFs" ))
