#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
#
# Author:    Yuansheng Sun  yuansheng-sun@uiowa.edu
# Copyright: University of Iowa 2006
#
# Filename:  SConscript
#

Import( 'env' )
env = env.Clone()

env.Append( LIBS = [ 'deconv', 'fftw3', 'fftw3f', 'gsl', 'blas' ] )
env.Append( LIBPATH = [ '#build/libdeconv' ] )

deconv3Dpsf = env.Program( 'deconv3Dpsf', 'deconv3Dpsf.cc' )
deconvRZpsf = env.Program( 'deconvRZpsf', 'deconvRZpsf.cc' )
deconvRZpsf_3Dpsf = env.Program( 'deconvRZpsf_3Dpsf', 'deconvRZpsf_3Dpsf.cc' )
deconvLW = env.Program( 'deconvLW', 'deconvLW.cc' )
deconvCG = env.Program( 'deconvCG', 'deconvCG.cc' )
deconvEM = env.Program( 'deconvEM', 'deconvEM.cc' )
deconvEMlik = env.Program( 'deconvEMlik', 'deconvEMlik.cc' )

env.Alias('install', env.Install( env['BIN_DIR'], deconv3Dpsf ))
env.Alias('install', env.Install( env['BIN_DIR'], deconvRZpsf ))
env.Alias('install', env.Install( env['BIN_DIR'], deconvRZpsf_3Dpsf ))
env.Alias('install', env.Install( env['BIN_DIR'], deconvLW ))
env.Alias('install', env.Install( env['BIN_DIR'], deconvCG ))
env.Alias('install', env.Install( env['BIN_DIR'], deconvEM ))
env.Alias('install', env.Install( env['BIN_DIR'], deconvEMlik ))
